import fs from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const style=`*{box-sizing:border-box}body{margin:0;background:#f6f7f9;color:#17191d;font:17px/1.7 -apple-system,BlinkMacSystemFont,'Apple SD Gothic Neo',sans-serif}header{padding:54px max(5vw,24px);background:#08090b;color:white}header small{color:#b8c4d4;letter-spacing:.12em}h1{font-size:clamp(32px,5vw,54px);line-height:1.2;max-width:1050px;margin:24px 0}h2{font-size:27px;margin:0 0 18px}h3{font-size:20px}main{max-width:1120px;margin:auto;padding:40px 24px}section{margin:0 0 32px;padding:32px;background:white;border:1px solid #d4dae3}p{max-width:85ch}a{color:#215bd2}header a{color:#c4d7ff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:26px}.flow{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.flow div{padding:18px;border:1px solid #d4dae3}table{border-collapse:collapse;width:100%;font-size:16px}td,th{padding:15px;text-align:left;border-bottom:1px solid #d4dae3;vertical-align:top}th{background:#102747;color:white}.table{overflow:auto}.note{font-size:15px;color:#536174}.current{background:#e8f0ff;color:#102747;font-weight:700}.bar{display:flex;flex-wrap:wrap;gap:12px;margin:20px 0}button{font:inherit;padding:10px 18px;color:white;background:#102747;border:0;cursor:pointer}[contenteditable]{outline:1px dashed #c4cfdf;padding:10px;min-height:80px;white-space:pre-wrap}pre{background:#102747;color:white;padding:20px;overflow:auto;font:15px/1.7 Menlo,monospace}.page{break-after:page}footer{padding:26px;text-align:center;color:#536174;font-size:14px}li{margin:8px 0}@media(max-width:700px){.grid,.flow{grid-template-columns:1fr}section{padding:22px}td,th{min-width:130px}}@media print{body{background:white;font-size:12pt}header{background:white;color:#17191d;padding:0 0 22px}header small{color:#536174}h1{font-size:28pt}main{padding:0}section{padding:12px 0;border:0;break-inside:avoid}.bar,footer{display:none}[contenteditable]{outline:0}th{background:#e8f0ff;color:#17191d}@page{size:A4;margin:18mm}}`;
const controls=`<div class="bar"><button onclick="window.print()">인쇄 / PDF 저장</button><button onclick="save()">작성본 HTML 저장</button></div><p class="note">이 파일 하나만 공유하면 됩니다. 외부 CSS·폰트·스크립트가 없습니다. 작성 내용은 서버로 전송하지 않습니다. 저장 버튼으로 편집본을 다운로드하세요.</p>`;
const script=`<script>function save(){const html='<!doctype html>'+document.documentElement.outerHTML;const u=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=document.title+'.html';a.click();URL.revokeObjectURL(u)}</script>`;
const section=(title,body,cls='')=>`<section class="${cls}"><h2>${title}</h2>${body}</section>`;
const edit=(s)=>`<div contenteditable="true" aria-label="${s}">${s}\n[직접 작성]</div>`;
const table=(heads,rows)=>`<div class="table"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
async function write(rel,title,sub,body){const target=path.join(root,rel);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${style}</style></head><body><header><small>LLMOPS / 2026-2</small><h1>${title}</h1><p>${sub}</p></header><main>${controls}${body}</main><footer>LLMOps 통합 강좌 · 기획과 증거 중심 · 2026년 2학기</footer>${script}</body></html>`)}
const web='curriculum/2026-2/web/';
const rules=table(['대상','구성','제출 경로'],[['아주대AI대학원','자원하여 구성한 2–4인 팀','<a href="https://docs.google.com/forms/d/e/1FAIpQLSd3UOP4SjCUct_RJKcgvVNGEBCpOOLmNkZPi6QFBIQAilKIag/viewform">팀 신청 Google Form</a> / 기획서 온라인 LMS'],['군산대·국립창원대 등 그 외','개인 프로젝트 진행 가능','공지된 교수자 이메일']]);
const rubric=table(['평가 항목','배점','확인 근거'],[['문제 정의·제안 가치','25','대상 사용자·현재 불편·선택 이유'],['사용 흐름·UX','20','핵심 흐름·예외·최소 기능·제외 범위'],['기술·데이터·운영','20','출처·권한·구조·비용·보류·복구'],['평가·검증 계획','20','기준선·대표 질의·성공/실패 기준'],['실행 범위·일정·역할','10','현실적인 주차별 산출물·담당·위험 대응'],['가독성·근거·구성','5','두괄식 요약·주장/근거 분리']]);
const submission=
section('8주차 · 제출물 평가',`<p>2026년 10월 23일. 중간고사와 실시간 수업 없이 온라인 기획서 제출만으로 평가합니다. 정확한 마감 시각·배점 적용은 소속별 공지를 우선합니다.</p>${rules}<p>팀 신청은 기획서 제출과 별개입니다. 다른 수강생의 이메일·전화번호는 공개하지 않습니다.</p>`)
+section('초안과 피드백 일정',table(['시점','해야 할 일','확인할 결과'],[['10월 8일(목)까지','4주차 과제 02 제출','검색 비교·실패 사례 정리'],['10월 9일(금)','한글날 휴일','강의·녹화영상·새 과제 없음'],['10월 16일(금) 7주차','팀 또는 개인 기획서 초안 제출','교수의 질문·피드백 기록'],['10월 23일(금) 8주차','피드백을 반영한 수정본 제출','온라인 제출물 평가 · 시험 없음']]))
+section('핵심 정보와 허용 형식',`<div class="flow"><div>01 제안 요약<br>누구의 어떤 문제·가치</div><div>02 제품 요구사항<br>기능·예외·완료 조건</div><div>03 평가·운영<br>지표·근거·리스크</div><div>04 로드맵<br>주차·담당·범위</div></div><p>2Pager(2페이지 제안 요약), PRD(Product Requirements Document, 제품 요구사항 문서), 로드맵의 핵심 정보가 있으면 PPT, Word 문서, Word에서 저장한 PDF, 독립형 HTML 등으로 제출할 수 있습니다. <strong>한글(HWP) 파일은 제출 형식에서 제외</strong>합니다. 여러 형식을 중복 제출할 필요는 없습니다.</p><p>PPT 5–8장 요약, 프로토타입 시안, 60–120초 데모 영상은 선택 자료입니다. 구현 완료나 유료 도구 사용을 요구하지 않습니다.</p>`)
+section('세 가지 설계 리뷰',`<div class="grid"><div><h3>대표·사업 관점</h3><p>왜 지금 필요한가? 기존 해결책보다 나은가? 사용자·성과·비용 가정이 현실적인가?</p><h3>UX 디자이너 관점</h3><p>입력에서 결과까지 이해 가능한가? 오류·대기·수정·답변 보류가 사용자에게 명확한가?</p></div><div><h3>개발자 관점</h3><p>데이터를 합법적으로 확보할 수 있는가? 재현 가능한 인터페이스·평가·버전·복구를 설계했는가?</p><p class="note">피드백은 특정 학생의 자동 성적 판정이 아니라 서비스 설계 개선을 위한 질문입니다.</p></div></div>`)
+section('평가 기준 · 100점',rubric)
+section('두괄식 문서',`<p>첫 화면에 서비스 제안·대상 사용자·해결 가치·최소 기능·성공 기준을 제시합니다. 주장은 근거와 함께 적고, 제작 과정·AI 도구 대화·질의응답 로그는 필요한 부분만 부록으로 분리합니다.</p><p>조사로 확인한 사실, 팀 가정, 향후 검증할 가설을 구분합니다. 프로토타입의 고정 응답을 실제 모델 성능으로 제시하지 않습니다.</p>`)
+section('조사·제작 도구',`<p>Gemini Deep Research 등으로 자료를 조사할 수 있으나 원문·작성일·출처를 재확인합니다. Codex와 Claude Code는 구현·테스트 보조 도구로 활용하고 생성 코드를 직접 검토합니다. Figma 또는 HTML로 사용자 흐름 시안을 만들 수 있습니다. 도구 선택은 자유이며 유료 구독은 필수가 아닙니다.</p><p><a href="https://support.google.com/gemini/answer/15719111?hl=en">Gemini Deep Research 공식 도움말</a> · <a href="https://developers.openai.com/codex/app/">Codex 공식 문서</a> · <a href="https://code.claude.com/docs/en/desktop">Claude Code 공식 문서</a></p>`)
+section('제출 전 점검',`<ol><li>팀 구성·대표 연락처·역할 또는 개인 작성자 확인</li><li>핵심 정보·사실/가설·데이터 출처 확인</li><li>평가 기준·대표 실패·보류 조건 확인</li><li>링크 보기 권한·파일 열기·PDF 가독성 확인</li><li>다른 사람 개인정보·토큰·실제 고객 자료 제거</li></ol><p><a href="project-proposal-2pager.html">2Pager 양식</a> · <a href="project-prd.html">PRD 양식</a> · <a href="examples/writing-coach-2pager.html">글쓰기 서비스 예시</a></p>`);
await write(web+'project-submission.html','8주차 프로젝트 기획서 제출 안내','시험 없는 온라인 기획서 평가 · 자유 형식 · 팀/개인 운영',submission);
const templateNotice=section('제출 일정과 형식',`<p>10월 16일 7주차에 초안 0.1을 먼저 제출하고 교수 피드백을 받습니다. 10월 23일 8주차에는 수정본 0.2를 제출·평가합니다. 아주대AI대학원 팀은 LMS, 다른 학교의 개인 프로젝트는 공지된 교수 이메일을 이용합니다. PPT·Word·Word 기반 PDF·HTML 가능, 한글(HWP) 제외. 정확한 마감 시각은 소속별 공지를 확인하세요.</p><p><a href="project-submission.html">제출 안내와 평가 기준</a></p>`);
await write(web+'project-proposal-2pager.html','2Pager · 프로젝트 제안 요약','제안·근거·범위를 한눈에 · 두 페이지 권장, 형식 강제 아님',templateNotice+section('01 제안·문제·가치',edit('한 문장 제안 / 대상 사용자 / 현재 해결 방식과 불편 / 근거 출처'))+section('02 사용자 흐름·최소 기능',edit('입력 → 핵심 처리 → 결과 → 사용자 수정 / 우선 기능 3개 / 제외 범위'),'page')+section('03 기술·데이터·평가',edit('데이터 출처·권한 / 간단한 구조 / 기준선 / 대표 평가 입력 / 성공·실패·보류 기준'))+section('04 실행 계획·요청',edit('8주차까지 확인한 근거 / 9–15주차 일정·담당 / 핵심 위험·대응 / 교수에게 확인할 질문')));
await write(web+'project-prd.html','PRD · 제품 요구사항 문서','Product Requirements Document · 구현 가능한 범위와 완료 조건',templateNotice+section('01 제품 요약',edit('제안 결론 / 사용자·상황 / 해결 목표 / 비목표'))+section('02 경험과 요구사항',edit('주요 사용자 흐름 / 요구사항 ID·우선순위·완료 조건 / 대기·오류·수정·보류'))+section('03 데이터·기술 구조',edit('데이터 출처·사용 권한·버전 / 처리 흐름·입출력 / 모델·검색·도구 선택 이유 / 인증·삭제·로그'))+section('04 품질·운영',edit('비교 기준선 / 개발·테스트 질의 / 품질·시간·비용 목표와 근거 / 실패 유형 / 복구·사람 검토'))+section('05 일정·검증 질문',edit('주차별 산출물·담당·완료 조건 / 위험과 대안 / 확인이 필요한 가설 / 부록·참고자료')));
const schedule=[['01','09.04','실시간 온라인','서비스 운영·실행 추적'],['02','09.11','실시간 온라인','프롬프트 설계·과제01'],['03','09.18','실시간 온라인','평가·실패 분류'],['04','09.25','추석 · 녹화 업로드','검색 증강 생성·과제02'],['05','10.02','실시간 온라인','검색 품질 개선'],['06','10.09','한글날 · 수업 없음','영상·신규 과제 없음'],['07','10.16','실시간 온라인','강의 재개·기획서 초안 제출·피드백'],['08','10.23','온라인 제출·평가만','수정 기획서 · 시험 없음'],['09','10.30','실시간 온라인','API 서비스'],['10','11.06','실시간 온라인','배포·실행 관찰'],['11','11.13','실시간 온라인','오프라인 평가'],['12','11.20','실시간 온라인','온라인 관찰·실험'],['13','11.27','실시간 온라인','안전·권한·거버넌스'],['14','12.04','실시간 온라인','비용·지연·용량'],['15','12.11','실시간 온라인','통합 점검·리허설'],['16','12.18','실시간 온라인 발표','프로젝트 결과·시연·질의응답']];
await write(web+'course-roadmap.html','16주 로드맵','정규 수업 온라인 · 6주차 휴일 · 7주차 초안 · 8주차 수정본',section('주차별 목표',table(['주차','금요일','진행 방식','핵심 내용'],schedule))+section('누적 포트폴리오',`<div class="flow"><div>1–3주<br>문제·입출력·추적</div><div>4–5주<br>데이터·검색·평가</div><div>6주<br>한글날 휴일</div><div>7–16주<br>초안·수정·구현·발표</div></div><p>각 강의 초반 현재 주차를 강조합니다. URL의 <code>?week=4</code> 또는 <code>?week=5</code>로 해당 주차를 표시합니다.</p><p><a href="project-submission.html">8주차 상세 제출 안내</a></p>`)+`<script>const w=Number(new URLSearchParams(location.search).get('week')||4);document.querySelectorAll('tbody tr').forEach(r=>{if(Number(r.firstElementChild.textContent)===w){r.classList.add('current');r.setAttribute('aria-current','true')}})</script>`);
const assignment=
section('목표',`<p>같은 합성 또는 사용 가능한 문서에서 검색 설정 하나만 바꾸고, 어떤 질의의 원문 근거와 순위가 달라졌는지 설명합니다. 검색 점수 상승과 실제 답변 가능성을 구분하고, 답을 보류해야 하는 질의도 확인합니다.</p>`)
+section('제출 경로와 마감',`<p><strong>2026년 10월 8일(목)까지</strong> 제출합니다. 원래 예정된 6주차 금요일 10월 9일의 전날입니다. 정확한 마감 시각은 소속별 공지를 확인하세요. 10월 9일은 한글날 휴일로 강의·녹화영상·신규 과제가 없고, 7주차 10월 16일 실시간 온라인 강의에서 학습을 이어갑니다.</p><p>아주대AI대학원생은 온라인 LMS, 군산대·국립창원대 등 다른 학교 학생은 공지된 담당 교수 이메일로 제출합니다. 공개 GitHub에는 개인 과제나 다른 사람의 개인정보를 올리지 않습니다.</p>`)
+section('실습 순서',`<ol><li>합성 또는 공개 사용 가능 문서 5개 이상, 질의 10개 이상 준비. 문서 ID·출처·버전·접근 범위를 적습니다.</li><li>답이 있는 질의, 없는 질의, 표현이 다른 질의, 접근 권한과 적용 날짜가 중요한 질의를 포함합니다.</li><li>분할 크기·겹침·검색 방식·후보 수를 고정하고 기준선 결과를 저장합니다. 개발 질의와 확인 질의를 구분합니다.</li><li>한 번에 변수 하나만 변경합니다. 변경 전후의 검색 문서 ID·순위·답변 보류를 비교합니다.</li><li>대표 실패 2개를 원문 위치와 함께 설명하고, 자기 프로젝트에 적용할 요구사항 3개를 작성합니다.</li></ol>`)
+section('비교를 읽는 예시',table(['조건','첫 관련 문서','답변','해석'],[['“돈은 언제 돌려줘요” · 기본 BM25','검색되지 않음','보류','질문과 문서의 표현 차이'],['같은 질의 · 동의어 확장','D03 · 1위','보류','검색 회수와 답변 조건은 별도'],['“상품 반품 기간” · 기본 BM25','D01 · 1위','원문 발췌','출처·적용 날짜까지 확인']]))
+section('제출물',`<p>실행 가능한 <code>.ipynb</code> 1개 이상, 짧은 HTML 또는 PDF 보고서, 비교 결과 JSON 또는 표, 화면 캡처 2장을 제출합니다. 사용 자료와 실행 방법을 적습니다. 실제 고객·다른 학생 개인정보·API 키는 넣지 않습니다.</p>`)
+section('평가 기준',table(['항목','점수'],[['실행·재현 가능성','30'],['한 변수 비교·실패 분석','30'],['원문 근거·출처·권한','20'],['프로젝트 요구사항·한계 설명','20']]))
+section('작성용 요약',edit('기준선 / 변경 하나 / 질의별 차이 / 실패 2개 / 요구사항 3개 / 한계·다음 검증'));
await write('week04/assignment/assignment02.html','과제 02 · 검색 근거와 개선','10월 8일(목)까지 · 6주차 휴일 이전 제출',assignment);
const sample=section('제안 결론',`<p>논증형 글쓰기 학습자를 위한 근거 기반 수정 코치. 글을 대신 완성하거나 자동 성적을 확정하지 않고, 작성자가 자기 글의 주장·근거·구조를 확인하고 수정하도록 지원합니다.</p>`)+section('사용자 문제·가설',`<p>가설: “잘 썼다”는 총평만으로는 어떤 문장을 고쳐야 하는지 파악하기 어렵습니다. 학습자 인터뷰와 수정 전후 과제로 검증합니다. 아직 확인하지 않은 수요를 시장 사실로 제시하지 않습니다.</p>`)+section('핵심 경험',`<div class="flow"><div>글 입력·평가 기준 선택</div><div>문단 역할·주장/근거 표시</div><div>인용 문장·수정 질문</div><div>사용자 수정·전후 비교</div></div>`)+section('분리된 평가 기준',table(['기준','관찰 항목'],[['서론','분위기·배경 / 발제 아이디어 / 제안·주장 예고'],['본론1','주장1 / 해당 근거 / 연결 설명'],['본론2','주장2 / 해당 근거 / 연결 설명'],['결론','아이디어 제언 / 두 주장 요약 / 새 근거의 무리한 추가 여부'],['유창성·이해','문장 연결·대명사·모호성 / 과제·자료 이해와 근거 연결']]))+section('검증과 운영',`<p>교수자 기준표 → 비식별 예문 → 근거 문장 대조 → 구조화된 출력 검증 → 사람 검토 → 학습자 수정. 형식 검증만으로 내용 타당성을 보장하지 않습니다.</p><p>최소 시제품: 기준표 1종·공개/합성 예문 20개·고정 테스트 입력·누락/잘못된 인용 분석. 평가자 간 불일치도 기록합니다. 성적 자동 결정·학생 순위화는 범위에서 제외합니다.</p><p>삭제 기능·접근 권한·동의 범위·보관 기간을 정의하고 실제 학생 글의 외부 모델 전송은 사전 승인 없이 하지 않습니다.</p>`)+section('개발 계획',`<p>9–10주 입력·근거 표시 시제품 / 11–12주 평가·실패 분석 / 13–14주 권한·삭제·비용 검증 / 15주 시연 점검 / 16주 실시간 발표. 목표 수치는 측정 가능한 가설로 제시하고 사전 실험 이후 정합니다.</p>`);
await write(web+'examples/writing-coach-2pager.html','글쓰기 수정 코치 · 2Pager 예시','수업용 기획 예시 · 검증 전 가설 · 자동 채점 서비스 아님',sample);
await write(web+'examples/writing-coach-prd.html','글쓰기 수정 코치 · PRD 예시','요구사항·출력·검증 기준의 분리',sample+section('요구사항',table(['ID','요구사항','완료 조건'],[['R01','문단·문장 위치 보존','원문 인용이 입력의 정확한 구간과 일치'],['R02','주장과 근거 별도 표시','각 주장은 근거 또는 근거 없음 상태 제공'],['R03','모호한 판정 보류','이유·확인 질문·사람 검토 경로 표시'],['R04','작성자 수정·전후 비교','사용자가 수정하고 변경 구간을 확인'],['R05','데이터 삭제','문서·검색 색인·캐시 삭제 범위 검증']])));
console.log('Standalone HTML files built');
